import type { ScenarioInput, ScenarioSuite } from "../schemas";
import { parseScenarioInput } from "../schemas";
import type { DiffAnalysis, DiffComplexity } from "./diffAnalyzer";

const complexityToMinScore = (complexity: DiffComplexity): number => {
	switch (complexity) {
		case "trivial":
			return 60;
		case "simple":
			return 70;
		case "moderate":
			return 75;
		case "complex":
			return 80;
	}
};

const buildInstructionFromDiff = (diff: DiffAnalysis): string => {
	const fileList = diff.files
		.filter((f) => !f.isDeleted)
		.map((f) => `  - ${f.path}`)
		.join("\n");

	return [
		`The following files need to be modified:\n${fileList}`,
		"",
		`Commit message: ${diff.commitMessage}`,
		"",
		`Task: Apply the change described in the commit message.`,
		`The change is categorized as: ${diff.category}`,
		`Expected complexity: ${diff.complexity} (approx. +${diff.totalAdditions}/-${diff.totalDeletions} lines)`,
	].join("\n");
};

export type GenerateScenarioFromDiffInput = {
	diff: DiffAnalysis;
	suite: ScenarioSuite;
	goldenPatchPath?: string;
};

export const generateScenarioFromDiff = (
	input: GenerateScenarioFromDiffInput,
): ScenarioInput => {
	const { diff, suite, goldenPatchPath } = input;
	const shortHash = diff.commitHash.slice(0, 8);

	return parseScenarioInput({
		id: `auto-${shortHash}`,
		suite,
		title: diff.commitMessage || `Auto-generated from ${shortHash}`,
		instruction: buildInstructionFromDiff(diff),
		targetFiles: diff.files
			.filter((f) => !f.isDeleted)
			.map((f) => f.path)
			.filter((p) => p.length > 0),
		expected: {
			mustPassTests: [],
			maxRiskErrors: 0,
			minScore: complexityToMinScore(diff.complexity),
		},
		goldenPatchPath,
		sourceCommit: diff.commitHash,
		autoGenerated: true,
	});
};
