import { describe, expect, test } from "bun:test";
import type { DiffAnalysis } from "../../../src/generators/diffAnalyzer";
import { generateScenarioFromDiff } from "../../../src/generators/scenarioGenerator";

const makeAnalysis = (overrides: Partial<DiffAnalysis> = {}): DiffAnalysis => ({
	commitHash: "abc1234567890def",
	commitMessage: "fix: resolve null pointer in parser",
	author: "Alice",
	date: "2026-01-01",
	files: [
		{
			path: "src/parser.ts",
			additions: 8,
			deletions: 3,
			isNew: false,
			isDeleted: false,
			isRenamed: false,
		},
	],
	totalAdditions: 8,
	totalDeletions: 3,
	complexity: "simple",
	category: "bugfix",
	isMergeCommit: false,
	...overrides,
});

describe("generateScenarioFromDiff", () => {
	test("generates scenario with correct id from commit hash", () => {
		const scenario = generateScenarioFromDiff({
			diff: makeAnalysis(),
			suite: "regression",
		});
		expect(scenario.id).toBe("auto-abc12345");
	});

	test("sets autoGenerated to true", () => {
		const scenario = generateScenarioFromDiff({
			diff: makeAnalysis(),
			suite: "regression",
		});
		expect(scenario.autoGenerated).toBe(true);
	});

	test("stores sourceCommit", () => {
		const scenario = generateScenarioFromDiff({
			diff: makeAnalysis(),
			suite: "smoke",
		});
		expect(scenario.sourceCommit).toBe("abc1234567890def");
	});

	test("uses commit message as title", () => {
		const scenario = generateScenarioFromDiff({
			diff: makeAnalysis(),
			suite: "regression",
		});
		expect(scenario.title).toBe("fix: resolve null pointer in parser");
	});

	test("sets goldenPatchPath when provided", () => {
		const scenario = generateScenarioFromDiff({
			diff: makeAnalysis(),
			suite: "regression",
			goldenPatchPath: "/tmp/abc12345.patch",
		});
		expect(scenario.goldenPatchPath).toBe("/tmp/abc12345.patch");
	});

	test("includes non-deleted files in targetFiles", () => {
		const analysis = makeAnalysis({
			files: [
				{
					path: "src/a.ts",
					additions: 5,
					deletions: 0,
					isNew: true,
					isDeleted: false,
					isRenamed: false,
				},
				{
					path: "src/b.ts",
					additions: 0,
					deletions: 3,
					isNew: false,
					isDeleted: true,
					isRenamed: false,
				},
			],
		});
		const scenario = generateScenarioFromDiff({
			diff: analysis,
			suite: "regression",
		});
		expect(scenario.targetFiles).toContain("src/a.ts");
		expect(scenario.targetFiles).not.toContain("src/b.ts");
	});

	test("minScore depends on complexity", () => {
		const trivial = generateScenarioFromDiff({
			diff: makeAnalysis({ complexity: "trivial" }),
			suite: "regression",
		});
		const complex = generateScenarioFromDiff({
			diff: makeAnalysis({ complexity: "complex" }),
			suite: "regression",
		});
		expect(trivial.expected.minScore).toBeLessThan(complex.expected.minScore);
	});

	test("instruction contains commit message and file list", () => {
		const scenario = generateScenarioFromDiff({
			diff: makeAnalysis(),
			suite: "regression",
		});
		expect(scenario.instruction).toContain("src/parser.ts");
		expect(scenario.instruction).toContain(
			"fix: resolve null pointer in parser",
		);
	});
});
